apiVersion: v1
kind: Service
metadata:
  name: {{ include "dns-bind.fullname" . }}-dns
  labels:
    {{- include "dns-bind.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceDns.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ default "ClusterIP" .Values.serviceDns.type }}
  {{- if .Values.serviceDns.clusterIP }}
  clusterIP: {{ .Values.serviceDns.clusterIP }}
  {{- end }}
  {{- if .Values.serviceDns.externalIPs }}
  externalIPs:
  {{ toYaml .Values.serviceDns.externalIPs | indent 4 }}
  {{- end }}
  {{- if or (eq .Values.serviceDns.type "NodePort") (eq .Values.serviceDns.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.serviceDns.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.serviceDns.loadBalancerIP }}
  loadBalancerIP: {{ .Values.serviceDns.loadBalancerIP }}
  {{- end }}
  ports:
    - port: 53
      targetPort: dns
      {{- if and (.Values.serviceDns.nodePort) (eq .Values.serviceDns.type "NodePort") }}
      nodePort: {{ .Values.serviceDns.nodePort }}
      {{- end }}
      protocol: TCP
      name: dns
    - port: 53
      targetPort: dns-udp
      {{- if and (.Values.serviceDns.nodePort) (eq .Values.serviceDns.type "NodePort") }}
      nodePort: {{ .Values.serviceDns.nodePort }}
      {{- end }}
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "dns-bind.selectorLabels" . | nindent 4 }}
