apiVersion: v1
kind: Service
metadata:
  name: {{ include "dns-bind.fullname" . }}
  labels:
    {{- include "dns-bind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceDns.type }}
  {{- if .Values.serviceDns.loadBalancerIP }}
  loadBalancerIP: {{ .Values.serviceDns.loadBalancerIP }}
  {{- end }}
  {{- if or (eq .Values.serviceDns.type "NodePort") (eq .Values.serviceDns.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.serviceDns.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: 53
      targetPort: dns
      {{- if .Values.serviceDns.nodePort }}
      nodePort: {{ .Values.serviceDns.nodePort }}
      {{- end }}
      protocol: TCP
      name: dns
    - port: 53
      targetPort: dns-udp
      {{- if and (.Values.serviceDns.nodePort) (eq .Values.serviceDns.type "NodePort") }}
      nodePort: {{ .Values.serviceDns.nodePort }}
      {{- end }}
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "dns-bind.selectorLabels" . | nindent 4 }}
