name: Build docker Image

env:
  IMAGE_PLATFORMS: linux/386,linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docker-image/**"

jobs:
  generate_tag:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - id: tag
        shell: bash
        run: |
          echo "Tag: $(git describe --abbrev=0)"
          echo "::set-output name=tag::$(git describe --abbrev=0)"
 
  build-image:
    runs-on: ubuntu-latest
    needs: generate_tag
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ env.IMAGE_PLATFORMS }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./docker-image/
          platforms: ${{ env.IMAGE_PLATFORMS }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ needs.generate_tag.outputs.output }}
