name: Build helm chart

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docker-image/**"
      - "helm/**"

jobs:
  generate_tag:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - id: tag
        shell: bash
        run: |
          echo "Tag: $(git describe --abbrev=0)"
          echo "::set-output name=tag::$(git describe --abbrev=0)"
 
  build-helm-chart:
    runs-on: ubuntu-latest
    needs: generate_tag
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check out helm-charts
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/helm-charts
          ref: 'gh-pages'
          token: ${{ secrets.HELM_REPO_TOKEN }}
          path: helm-charts

      - name: Configure Git
        working-directory: helm-charts
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Update chart application version
        run: |
          sed -i -e "s/appVersion:.*/appVersion: ${{ needs.generate_tag.outputs.output }}/g" helm/Chart.yaml

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: ./
          config: cr.yml
          charts_repo_url: https://fullstack-devops.github.io/helm-charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          HELM_REPO_TOKEN: "${{ secrets.HELM_REPO_TOKEN }}"
