name: Build helm chart

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docker-image/**"
      - "helm/**"

jobs:
  generate_infos:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.version }}
      tag: ${{ steps.tag.outputs.tag }}
      pr: ${{ steps.tag.outputs.pr }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup awesome-ci
        uses: fullstack-devops/awesome-ci-action@main

      - name: set build Infos
        run: awesome-ci pr info -number ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: export Infos
        id: tag
        shell: bash
        run: |
          echo "Tag: $(git describe --abbrev=0)"
          echo "::set-output name=tag::$(git describe --abbrev=0)"
          echo "::set-output name=version::$ACI_VERSION"
          echo "::set-output name=pr::$ACI_PR"
 
  build-helm-chart:
    runs-on: ubuntu-latest
    needs: generate_tag
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Check out helm-charts
        uses: actions/checkout@v2
        with:
          repository: fullstack-devops/helm-charts
          token: ${{ secrets.HELM_REPO_TOKEN }}
          ref: gh-pages
          persist-credentials: true
          path: helm-charts
      
      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.2

      - name: Helm Package
        run: helm package ./helm --version "${{ needs.generate_tag.outputs.release_version }}" --app-version "${{ needs.generate_tag.outputs.release_version }}" -d out/
      
      - name: Helm 
        env:
          GITHUB_TOKEN: ${{ secrets.HELM_REPO_TOKEN }}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          helm repo index out/ --url https://github.com/fullstack-devops/helm-charts/releases/download/excalidraw-1.0.1/excalidraw-1.0.1.tgz --merge helm-charts/index.yaml
          
          CHART_PACKAGE_NAME="my-chart-0.1.0+$(git rev-parse --short "$GITHUB_SHA").tgz"
          cd helm-chart-repository
          git add "$CHART_PACKAGE_NAME"
          git commit -m "$CHART_PACKAGE_NAME"
          git push origin main
